Added IRIS support
ensdomains/address-encoder pull request #180
Opened 2020-10-06 21:01 UTC by iRhonin

## Issue number

Closes #165

## List of features added/changed

- IRIS encoder/decoder based on bech32

## Reference
[IRIS is built on top of cosmos-sdk](https://www.irisnet.org/docs/)

## How Has This Been Tested?
- Using bech32 to generate hex format

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

2020-10-07 01:24 UTC, Arachnid commented
I have updated the Travis build to check that entries in the formats, tests, and README lists are in the correct order. Please check your PR and update it to maintain correct ordering in these lists.

2020-11-23 11:01 UTC, makoto requested changes

2020-11-23 11:01 UTC, makoto commented on README.md
> +
Please remove extra whitespace

2020-11-23 11:01 UTC, makoto commented
@iRhonin Please resolve conflicts

2020-11-23 11:43 UTC, iRhonin commented
@makoto done.

2020-11-23 19:34 UTC, makoto commented
Sorry but I noticed that this one came first https://github.com/ensdomains/address-encoder/pull/175

2020-11-23 19:34 UTC, closed without merging