Add support for ARDR address encoding and decoding functionality
ensdomains/address-encoder pull request #235
Opened 2020-10-09 14:32 UTC by janus

## Issue number
167
https://github.com/ensdomains/address-encoder/issues/167

## Description
ARDR addresses can be decoded or encoded. 

## List of features added/changed
- ardrCheckSum 
- ardrAddressDecoder
- ardrAddressEncoder
- cwmap
- alphabet
- gmult
- gexp
- glog
- getConfig('ARDR', 1200, ardrAddressEncoder, ardrAddressDecoder)

## How Has This Been Tested?
Add ARDR in the test pool so that decoded address should match it text version

## Checklist:

- [X ] My code follows the code style of this project.
- [ X] My code implements all the required features.

2020-10-26 11:19 UTC, makoto requested changes
Please provide the reference link to your specification.

2020-10-26 11:19 UTC, makoto commented on src/__tests__/index.test.ts
> +    coinType: 1200,
Can you let me know where did you get the cointype? According to SLIP0044, it's 16754

https://github.com/satoshilabs/slips/blob/master/slip-0044.md

2020-10-26 11:25 UTC, janus commented
Resolved. Thanks

2020-10-27 18:14 UTC, makoto commented
`Please provide the reference link to your specification.` this is still missing. Thanks.

2020-10-27 22:01 UTC, janus commented
Thanks. Resolved.

2020-11-17 13:27 UTC, makoto commented
Please fix the eslint failure https://travis-ci.com/github/ensdomains/address-encoder/jobs/407210200

2020-11-25 09:31 UTC, makoto commented
Any update on this? I will try to priortise reviewing your PRs so please fix any outstanding test failures or merge conflicts.

2020-11-26 10:44 UTC, janus commented
@makoto  Please go through and close.

2020-11-26 11:42 UTC, makoto commented
Note to myself about ADDR address format https://ardordocs.jelurida.com/RS_Address_Format

2020-11-26 11:42 UTC, merged