Add support for GXC address encoding and deconding functionalities
ensdomains/address-encoder pull request #238
Opened 2020-10-12 10:31 UTC by janus

## Issue number
196
https://github.com/ensdomains/address-encoder/issues/196

## Description
When converted to a string, checksum calculated as the first 4 bytes ripemd160( address ) is appended to the binary address before converting to base58 Encoder string and the result is appended to the prefix, "GXC". 
To Decode , the first 3 bytes must match the prefix, 'GXC' , then removed. And the the rest  is decoded with base58 Decoder. However, the last 4 bytes are for checksum and should be remove. The remaining ripemd160'd , with its first 4 bytes matching the checksum.

## List of features added/change
- gxcAddressEncoder
- gxcAddressDecoder
- getConfig('GXC', 53890, gxcAddressEncoder, gxcAddressDecoder)

## How Has This Been Tested?
Add GXC in the test pool so that decoded address should match it text version

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

2020-10-26 10:32 UTC, makoto commented on src/__tests__/index.test.ts
> +      { text: 'GXC6UKk9URcsCuGxLuRDqEuGzAqDkgKbG8AuWXFXsyzc2r9z7A1kw', hex: '02d085655f8060a79a4b12b14e442b8a554ba867bdadce3c2dc39e1a42a01827c0' },
Can you let me know where did you find the test text/hex and coinType? According to SLIP44, the coin type of GXC is 2303, not 53890 https://github.com/satoshilabs/slips/blob/master/slip-0044.md

2020-10-26 10:33 UTC, makoto requested changes
https://github.com/ensdomains/address-encoder/pull/238/files#r511860654

2020-10-26 10:57 UTC, janus commented
Thanks. Done.

2020-11-17 13:13 UTC, makoto commented on src/index.ts
> +  const RIPEMD160 = require('ripemd160');
Please `import` at the top of the file

2020-11-17 13:17 UTC, makoto commented on src/index.ts
> +  const RIPEMD160 = require('ripemd160');
Please `import` at the top of the file

2020-11-17 20:13 UTC, janus commented
I don't understand this failure related to crypto module. It seems it is trying to install it ...
https://travis-ci.com/github/ensdomains/address-encoder/jobs/441897423

2020-11-17 20:58 UTC, janus commented
@makoto  Check CI configuration

2020-11-23 13:52 UTC, janus commented
@makoto  This current error coming from Travis CI would be needing your help. It worked for me when I use this command `sudo npm i`. I am use  node v14 but I don't think it would be different because I also encountered same with node v10. 


```
npm install

> @ensdomains/address-encoder@0.2.0 prepare /home/travis/build/ensdomains/address-encoder

> npm run build

> @ensdomains/address-encoder@0.2.0 build /home/travis/build/ensdomains/address-encoder

> microbundle --external crypto

(Rollup Core plugin) Error: Could not load stream (imported by /home/travis/build/ensdomains/address-encoder/node_modules/hash-base/index.js): ENOENT: no such file or directory, open 'stream'

Error: Could not load stream (imported by /home/travis/build/ensdomains/address-encoder/node_modules/hash-base/index.js): ENOENT: no such file or directory, open 'stream'

```

2020-11-25 09:14 UTC, makoto commented
@janus Please try again. We merged https://github.com/ensdomains/address-encoder/pull/248 which removed dependency of `crypto`

2020-11-26 08:36 UTC, janus commented
@makoto  Updated. Please go through.

2020-11-26 11:04 UTC, janus commented
@makoto Resolved. Go through and close

2020-11-26 11:05 UTC, janus commented on src/index.ts
> +  const RIPEMD160 = require('ripemd160');
Resolved

2020-11-26 12:04 UTC, merged