Filecoin support
ensdomains/address-encoder pull request #242
Opened 2020-10-27 15:42 UTC by makoto

## Issue number

https://github.com/ensdomains/address-encoder/issues/85

## Description

## Reference to the specification

- [filecoin project spec page](https://spec.filecoin.io/#section-glossary.address)
- [go implementation](https://github.com/filecoin-project/go-address/blob/master/address.go)

## List of features added/changed

-  Include `@glif/filecoin-address` and define module
- Add filAddrEncoder/filAddrDecoder
- Add test

## How Has This Been Tested?

Unit test 

## Anything 

The file size increased from  760188  to 861221 as it included external lib

## Screenshots (if appropriate):

<img width="1475" alt="Screenshot 2020-10-27 at 15 37 49" src="https://user-images.githubusercontent.com/2630/97325198-a2b06000-186a-11eb-8c27-56aa72038dbe.png">

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My code implements all the required features.

2020-10-29 23:07 UTC, Arachnid requested changes
100k is a *lot* for a single cryptocurrency, and looking at the imported library it looks like the address format is fairly straightforward and only relies on blake2b and base32 - both of which I think we already import for other coins. Would it be possible to import the relevant code (with license/citation) into the address-encoding library instead?

2020-10-29 23:07 UTC, Arachnid commented on src/index.ts
> +  const address = filNewAddress('1', data)
Pretty sure we shouldn't be hardcoding version 1 here. From looking at the library, it looks like the first byte in the binary format is the version byte, and we should probably be preserving that instead.

2020-10-29 23:07 UTC, Arachnid commented on README.md
> + - FIL ([bls](https://spec.filecoin.io/#section-glossary.address))
BLS is the signature scheme, not the address encoding; the address encoding is base32 + blake2b checksum

2020-11-05 19:29 UTC, makoto commented
@Arachnid when I ported the library and reused `blake2b` and `base32`, the file size went back to `762186`. https://travis-ci.com/github/ensdomains/address-encoder/jobs/428828727
However , filecoin protocol 0 (ID) requires `leb128` lib and with that the file size went back to `856420`. Not sure if porting also `leb128` will reduce file sizes as there aren't overwrapping libraries we can reuse https://gitlab.com/mjbecze/leb128/-/blob/master/package.json .

2020-11-11 02:23 UTC, Arachnid commented
It looks like leb128 is only as large as it is because it imports bn.js. Surely that must already be in our transitive dependencies somewhere - possibly a different version?

2020-11-16 20:12 UTC, makoto commented
Ok, ported `leb128`. The filesize is now shrunk a bit `760188 -> 732656` for some reason.

2020-11-16 21:07 UTC, Arachnid approved these changes

2020-11-16 21:08 UTC, merged