Return  any non registered evmchain coin types as ETH
ensdomains/address-encoder pull request #374
Opened 2023-02-15 18:37 UTC by makoto

This change extends `formatsByCoinType` to return ETH encoder/decoder even when specific evm chain id is not registered.

Example:
```js
// registered
encoder.formatsByCoinType[encoder.convertEVMChainIdToCoinType(100)]
{
  coinType: 2147483748,
  decoder: [Function (anonymous)],
  encoder: [Function (anonymous)],
  name: 'GNO'
}
// non registered
encoder.formatsByCoinType[encoder.convertEVMChainIdToCoinType(100123)]
{
  coinType: 2147583771,
  decoder: [Function (anonymous)],
  encoder: [Function (anonymous)],
  name: ''
}
```

## TODO

Currently `convertEVMChainIdToCoinType` expects that coinType is up to 0xffffffff(4294967295) so any larger chainid starts returning incorrect coinType

Example
```
// correct
> encoder.convertEVMChainIdToCoinType(2147483647)
4294967295
// incorrect
> encoder.convertEVMChainIdToCoinType(2147483648)
2147483648
```

We should either slow error for out of bounds, or change `convertEVMChainIdToCoinType` to return coinType larger than 0xffffffff

2023-02-20 02:03 UTC, Arachnid requested changes
Can you also please lint/format the code consistently?

2023-02-20 02:03 UTC, Arachnid commented on src/index.ts
> +  }
```suggestion
  if( coinType & SLIP44_MSB == 0 ){
    throw Error(`coinType ${coinType} is not an EVM chain`)
  }
```

2023-02-20 02:03 UTC, Arachnid commented on src/index.ts
>    return  ((SLIP44_MSB -1) & coinType) >> 0
```suggestion
  return  ((SLIP44_MSB - 1) & coinType) >> 0
```

2023-02-20 02:03 UTC, Arachnid commented on src/index.ts
>  type EnCoder = (data: Buffer) => string;
```suggestion
export const SLIP44_MSB = 0x80000000
type EnCoder = (data: Buffer) => string;
```

2023-02-20 02:03 UTC, Arachnid commented on src/index.ts
> +    }else if(coinType > SLIP44_MSB && coinType < EVM_MSB){
```suggestion
    }else if(coinType & SLIP44_MSB  != 0){
```

2023-02-20 10:14 UTC, makoto commented
> Can you also please lint/format the code consistently?

lint is part of CI and it did pass. Maybe need to add new rules?

2023-02-20 10:50 UTC, makoto commented
@Arachnid PTAL

2023-02-21 03:45 UTC, Arachnid commented
> lint is part of CI and it did pass. Maybe need to add new rules?

Great - but the formatting is very inconsistent. Can you prettyprint it?

2023-02-21 03:46 UTC, Arachnid approved these changes

2023-02-21 09:02 UTC, merged